# Site settings
author: Andrew Witmer
title: A Beginner's Walk through Software Engineering
header-img: img/home-bg.png
email: andrew.witmer445@gmail.com
copyright_name: Andrew Witmer
description: > # this means to ignore newlines until "baseurl:"
  Lessons of the Past & Thoughts of the Future
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  arwitmer

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
